- app/Http/Controllers/API/V1/MembersInvitationController.php
- app/Http/Controllers/API/V1/MessageController.php
- app/Http/Controllers/API/V1/TeamController.php
- app/Models/SupportChat.php
- app/Models/SupportMessage.php
- app/Services/MessageService.php
- app/Services/TeamService.php
- config/cors.php
- routes/api.php
Support Chat system implemented
> Support Chat system implemented

- app/Http/Controllers/API/V1/MembersInvitationController.php
- app/Services/MemberInvitationService.php
- routes/api.php
> Member Request Delete API

- app/Http/Controllers/API/V1/AllNotificationController.php
- chat_nodejs/index.js
- routes/api.php
node js write lost code and make an API for list
> node js write lost code and make an API for list

- app/Services/TeamService.php
> count issue fix Team

- app/Http/Controllers/API/V1/MembersInvitationController.php
- app/Services/MemberInvitationService.php
- app/Services/UserService.php
- db/team_member_invitations.sql
- routes/api.php
2. Search api
3. Team invitation update api
4. Team count limit
> 1. Return id in team-invite-member

- app/Services/UserService.php
> update API Team wise

- database/migrations/2021_12_20_154958_create_chats_table.php
- database/migrations/2021_12_20_155029_create_messages_table.php
- database/migrations/2021_12_20_155313_create_team_chats_table.php
- database/migrations/2021_12_20_155329_create_team_messages_table.php
- database/migrations/2021_12_20_155348_create_team_to_team_messages_table.php
- database/migrations/2021_12_20_155439_create_team_to_team_private_messages_table.php
- db/matv2.sql
> added migration files

- app/Services/MessageService.php
> Fix chat api issue

- chat_nodejs/index.js
> Add Typing Event

- chat_nodejs/index.js
> Update Notification Event

- app/Http/Controllers/API/V1/AllNotificationController.php
- database/migrations/2021_12_25_123732_create_all_notifications_table.php
- db/all_notifications.sql
> added migration file

- app/Http/Controllers/API/V1/AllNotificationController.php
- app/Http/Controllers/API/V1/TeamMembersController.php
> api update

- app/Http/Controllers/API/V1/AllNotificationController.php
- app/Http/Controllers/API/V1/MessageController.php
- app/Services/MessageService.php
- composer.lock
- routes/api.php
> seen not msg

- app/Http/Controllers/API/V1/MessageController.php
- app/Models/Generic.php
- routes/api.php
seen msg api update and generic class added
> seen msg api update and generic class added

- .gitignore
- app/Services/CandidateService.php
- app/Services/UserService.php
- app/Transformers/CandidateTransformer.php
- app/Transformers/RepresentativeTransformer.php
Git Ignore : Add config/cors.php to git ignore to avoid conflict
> Candidate info : Add Other image info

- app/Http/Controllers/API/V1/MessageController.php
- app/Models/Generic.php
- app/Models/TeamChat.php
- app/Models/TeamConnection.php
- app/Models/TeamToTeamMessage.php
- app/Services/MessageService.php
- database/migrations/2021_12_31_134727_add_team_connection_id_to_team_chats_table.php
- routes/api.php
connected team chat msg update
> connected team chat msg update

- app/Services/MessageService.php
> Team Connection Update

- app/Http/Controllers/API/V1/MessageController.php
- app/Models/TeamPrivateChat.php
- app/Models/TeamToTeamPrivateMessage.php
- app/Services/MessageService.php
- chat_nodejs/index.js
- routes/api.php
> Private Chat Request

- chat_nodejs/index.js
- database/migrations/2021_12_29_161311_create_team_to_team_messages_table.php
- database/migrations/2022_01_02_155216_create_team__private_chats.php
> add new table migration

- app/Http/Controllers/API/V1/MessageController.php
- app/Services/MessageService.php
> FIX PRIVATE CHAT HISTORY

- app/Services/TeamService.php
> add Team Image

- app/Http/Controllers/API/AdminDashboardController.php
- app/Models/User.php
- routes/api.php
> approved or reject

- database/seeders/AdminSeeder.php
> Admin Login

- app/Http/Controllers/API/AdminDashboardController.php
- app/Http/Controllers/API/V1/TeamController.php
- app/Http/Controllers/API/V1/UserController.php
- app/Models/RejectedNote.php
- app/Models/User.php
- app/Services/TeamService.php
- database/migrations/2022_01_10_070757_create_team_private_chats_table.php
- database/migrations/2022_01_10_070816_create_support_chats_table.php
- database/migrations/2022_01_10_070835_create_support_messages_table.php
- database/migrations/2022_01_10_071247_create_rejected_notes_table.php
- database/seeders/SupportAdmin.php
- routes/api.php
> Admin team

- app/Services/MessageService.php
Update Individual Support chat history
> Update Individual Support chat history

- app/Services/TeamService.php
> Active Team API Fix

- app/Services/TeamService.php
> fix team active code

- app/Http/Controllers/API/AdminDashboardController.php
update verify or rejected user
> update verify or rejected user

- app/Http/Controllers/API/V1/AllNotificationController.php
- routes/api.php
Admin Send Global Notification
> Admin Send Global Notification

- app/Http/Controllers/API/AdminDashboardController.php
- app/Http/Controllers/API/V1/UserController.php
- routes/api.php
> individual rejected Notes

- app/Services/MessageService.php
> Recent Chat

- app/Http/Controllers/API/AdminDashboardController.php
- app/Models/User.php
> Fix rep Info

- app/Http/Controllers/API/AdminDashboardController.php
- app/Services/TeamService.php
> Team create Fix

- app/Http/Controllers/API/AdminDashboardController.php
> Admin User Filtering

- app/Services/TeamConnectionService.php
- app/Services/TeamService.php
Asssociate data delete with team
> Asssociate data delete with team

- app/Http/Resources/TeamConnectionResource.php
- app/Services/TeamConnectionService.php
> connection report issue fix

- app/Http/Controllers/API/AdminDashboardController.php
- app/Services/TeamService.php
> Admin Pagination

- app/Services/TeamMemberService.php
> team leave

- app/Http/Controllers/API/V1/MessageController.php
- app/Services/MessageService.php
Update Team Chat API and fix issue
> Update Team Chat API and fix issue

- app/Services/MessageService.php
> team chat image update

- app/Models/Team.php
- app/Services/MessageService.php
connected team chat image update
> connected team chat image update

- app/Services/MessageService.php
- app/Services/TeamService.php
- app/Services/UserService.php
> image update with base url

- app/Services/MessageService.php
Private and recent chat image update
> Private and recent chat image update

- app/Services/AccessRulesDefinitionService.php
> role power update

- app/Http/Controllers/API/AdminDashboardController.php
> User List Update

- app/Http/Controllers/API/AdminDashboardController.php
- app/Models/User.php
- app/Services/MessageService.php
- routes/api.php
> User List U[pdate

- app/Http/Controllers/API/V1/PackageController.php
> plan api fix

- app/Http/Controllers/API/V1/PackageController.php
- app/Models/Team.php
- app/Services/TeamService.php
subscription Update and Team List Update
> subscription Update and Team List Update

- app/Services/TeamService.php
- database/migrations/2022_02_01_155210_create_visits_table.php
> fix team list

- app/Http/Controllers/API/V1/SubscriptionController.php
- app/Services/SubscriptionService.php
> update expiry date

- app/Http/Controllers/API/V1/VisitController.php
- app/Models/Visit.php
- database/migrations/2022_02_01_155210_create_visits_table.php
- routes/api.php
> vistor count and make graph

- database/migrations/2022_02_04_030331_add_team_connection_id_to_team_private_chats_table.php
> add migration

- app/Http/Controllers/API/AdminDashboardController.php
> relational data loaded

- app/Services/SubscriptionService.php
> subscription date fix

- app/Services/MessageService.php
> update support team list

- app/Http/Controllers/API/V1/SubscriptionController.php
- app/Mail/SubscriptionMail.php
- app/Services/SubscriptionService.php
- resources/views/emails/subscription/expiring_subscription.blade.php
- routes/api.php
- routes/web.php
> Subscription Mail

- app/Http/Controllers/API/AdminDashboardController.php
- app/Services/UserService.php
- database/migrations/2022_02_23_114049_modify_users_table.php
- db/query.txt
- routes/api.php
Approve or suspend user, active user list
> Approve or suspend user, active user list

- app/Services/MemberInvitationService.php
- app/Services/TeamService.php
> check user sstatus in team

- app/Http/Controllers/API/AdminDashboardController.php
- app/Transformers/RepresentativeTransformer.php
> fix user info

- app/Http/Controllers/API/AdminDashboardController.php
- routes/api.php
> Update user info api

- app/Services/MemberInvitationService.php
- app/Services/TeamService.php
Comment validation check Team create and join
> Comment validation check Team create and join

- app/Http/Controllers/API/AdminDashboardController.php
- app/Models/CandidateInformation.php
- db/query.txt
> API Update as per request

- app/Http/Controllers/API/AdminDashboardController.php
> add user obj in rep

- app/Services/MemberInvitationService.php
> update API join invitation

- app/Http/Controllers/API/AdminDashboardController.php
> upfate by deleted status

- app/Services/UserService.php
> update login response

- app/Services/UserService.php
update 403 as per req of samir bhai
> update 403 as per req of samir bhai
